export interface Product {
  id: string
  name: string
  sku: string
  category: string
  brand: string
  image: string
  description: string
  specs: Record<string, string>
  hsn: string
  minOrderQty: number
  inStock: boolean
  isOffer?: boolean
  offerBadge?: string
  features?: string[]
  application?: string
  cta?: string
}

export const categories = [
  { id: "lifting", name: "Automotive Lifting & Handling Equipment", icon: "ArrowUpCircle", description: "Lifts, floor jacks, cranes and stand systems" },
  { id: "collision-repair", name: "Body Repair & Dent Pulling Equipment", icon: "Hammer", description: "Frame straighteners and dent pulling systems" },
  { id: "welding", name: "Welding & Cutting Equipment", icon: "Zap", description: "Professional MIG/MAG welders and cutters" },
  { id: "cleaning", name: "Air, Cleaning & Workshop Utilities", icon: "Wind", description: "Compressors, vacuums and utilities" },
  { id: "painting", name: "Paint, Polishing & Surface Finishing", icon: "Paintbrush", description: "Spray guns and detailing systems" },
  { id: "tyre-service", name: "Tyre & Inflation Systems", icon: "Disc", description: "Nitrogen generation and digital inflators" },
  { id: "power-tools", name: "Power Tools (Corded & Cordless)", icon: "Zap", description: "Drills, grinders and impact wrenches" },
  { id: "measurement", name: "Measuring, Diagnostic & Precision Tools", icon: "Ruler", description: "Multimeters, gauges and calipers" },
  { id: "hand-tools", name: "Hand Tools & Workshop Accessories", icon: "Wrench", description: "Wrenches, sets and workshop accessories" },
]

export const brands = [
  "LINICH", "CAR-O-LINER", "SATA", "DeVilbiss", "3M", "Bosch", "Stanley", "DeWALT", "Fluke", "Mitutoyo", "PCL", "ACCURA", "Mirka", "MaxShine", "Menzerna", "Rexter", "JTC", "Blue Point", "Generic"
]

export const products: Product[] = [
  // ========================
  // 1. AUTOMOTIVE LIFTING & HANDLING
  // ========================
  {
    id: "lifting-1",
    name: "LINICH 4 Tons Hydraulic Two Post Lift",
    sku: "LIN-H2PL-4T",
    category: "lifting",
    brand: "LINICH",
    image: "/hydraulic-two-post-lift.png",
    description: "Professional heavy-duty hydraulic two-post lift with 4000 kg capacity, featuring double-cylinder lifting system and robotic welding for maximum durability.",
    specs: { "Capacity": "4000 kg", "Max Height": "1900 mm", "Material": "5 mm steel plates" },
    features: [
      "Lifting capacity of 4000 kgs",
      "Double-cylinder hydraulic lifting system",
      "Robotic welding for structural integrity",
      "Italian seals and chrome-plated rods",
      "Includes car door opening protection pads"
    ],
    application: "General vehicle service, underbody repairs",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-2",
    name: "LINICH 5 Ton Floor Jack",
    sku: "LIN-FJ-5T",
    category: "lifting",
    brand: "LINICH",
    image: "/linich-floor-jack-5t.png",
    description: "Industrial-grade hydraulic floor jack with 5-ton capacity, featuring a heavy-duty hydraulic system and long handle for effortless pumping.",
    specs: { "Capacity": "5 Ton", "System": "Heavy-duty Hydraulic" },
    features: ["5 Ton lifting capacity", "Long handle for leverage", "Stable wide base"],
    application: "Commercial vehicle maintenance",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-3",
    name: "LINICH 3 Ton Axle Stand",
    sku: "LIN-AS-3T",
    category: "lifting",
    brand: "LINICH",
    image: "/linich-axle-stand-3t.png",
    description: "Reliable 3-ton axle stands with ratchet-type adjustment and a wide stable base, essential for safely supporting vehicles.",
    specs: { "Capacity": "3 Ton", "Adjustment": "Ratchet-type" },
    features: ["Safety pin lock system", "Durable cast iron support", "Wide steel base"],
    application: "Vehicle support during repair",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-4",
    name: "LINICH Engine Crane (2 Ton)",
    sku: "LIN-EC-2T",
    category: "lifting",
    brand: "LINICH",
    image: "/linich-engine-crane-2t.png",
    description: "Heavy-duty steel engine crane with foldable design and mobile base for efficient engine lifting.",
    specs: { "Capacity": "2 Ton", "Frame": "Foldable" },
    features: ["Foldable design for storage", "Four position boom", "Heavy duty casters"],
    application: "Engine removal and installation",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-5",
    name: "LINICH Engine Crane (3 Ton)",
    sku: "LIN-EC-3T",
    category: "lifting",
    brand: "LINICH",
    image: "/linich-engine-crane-3t.png",
    description: "Industrial-grade engine crane for heavy vehicle engine service with maximum stability.",
    specs: { "Capacity": "3 Ton" },
    features: ["High lifting reach", "Reinforced steel structure", "Safe hydraulic control"],
    application: "Truck engine service",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-6",
    name: "LINICH Transmission Jack (0.5 Ton)",
    sku: "LIN-TJ-05T",
    category: "lifting",
    brand: "LINICH",
    image: "/linich-transmission-jack-05t.png",
    description: "Compact hydraulic transmission jack with 0.5 Ton capacity, featuring a stable wheeled base.",
    specs: { "Capacity": "0.5 Ton", "Type": "Standard Vertical" },
    features: ["Foot operated pump", "Adjustable saddle", "Safety chain included"],
    application: "Transmission service",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-7",
    name: "LINICH Transmission Jack (1 Ton)",
    sku: "LIN-TJ-1T",
    category: "lifting",
    brand: "LINICH",
    image: "/linich-transmission-jack-1t.png",
    description: "Professional hydraulic transmission jack with 1 Ton capacity and adjustable saddle for heavy-duty support.",
    specs: { "Capacity": "1 Ton" },
    features: ["Dual handle control", "Wide tripod base", "Heavy-duty wheels"],
    application: "Heavy transmission repair",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-8",
    name: "LINICH Engine Stand (450 Kg)",
    sku: "LIN-ES-450",
    category: "lifting",
    brand: "LINICH",
    image: "/linich-engine-stand.png",
    description: "360-degree rotating engine stand for safe engine mounting and easy rebuilding access.",
    specs: { "Capacity": "450 Kg", "Rotation": "360°" },
    features: ["Lockable rotation", "Universal mounting arms", "Stable T-base"],
    application: "Engine rebuilding",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-9",
    name: "Stanley Tool Trolley",
    sku: "STAN-TROLLEY",
    category: "lifting",
    brand: "Stanley",
    image: "/stanley-tool-trolley-v3.png",
    description: "Heavy-duty steel tool storage trolley with multi-drawer configuration and smooth-rolling casters.",
    specs: { "Material": "Steel", "Drawers": "Multiple" },
    features: ["Ball bearing slides", "Keyed locking system", "Ergonomic push handle"],
    application: "Workshop tool organization",
    cta: "Enquire Now",
    hsn: "9403",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-10",
    name: "Wheel Dolly (Pair)",
    sku: "GEN-WD-HD",
    category: "lifting",
    brand: "Generic",
    image: "/wheel-dolly-hd.png",
    description: "Heavy-duty steel wheel dolly designed for easy maneuvering of vehicles in tight spaces.",
    specs: { "Capacity": "Heavy-duty", "Material": "Steel" },
    features: ["360° swivel casters", "Recessed wheel well", "Brake locks"],
    application: "Vehicle positioning",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "lifting-11",
    name: "Car Creeper",
    sku: "GEN-CC-PRO",
    category: "lifting",
    brand: "Generic",
    image: "/car-creeper-v2.png",
    description: "Comfortable low-profile car creeper with padded surface and smooth-rolling wheels.",
    specs: { "Type": "Low-profile", "Padded": "Yes" },
    features: ["Rugged frame", "Oil resistant padding", "Six wheel glide"],
    application: "Under-vehicle work",
    cta: "Enquire Now",
    hsn: "9403",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 2. BODY REPAIR & DENT PULLING
  // ========================
  {
    id: "body-1",
    name: "LINICH 3100 Automatic Dent Puller",
    sku: "LIN-3100",
    category: "collision-repair",
    brand: "LINICH",
    image: "/linich-3100-auto-puller.png",
    description: "Automatic dent pulling machine designed for body repair with high welding power and precise control.",
    specs: { "Voltage": "220V", "Current": "3000A" },
    features: ["Automatic triggering", "German-made components", "Mobile trolley design"],
    application: "Collision repair",
    cta: "Enquire Now",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "body-2",
    name: "LINICH SPOT LCR 70",
    sku: "LIN-LCR70",
    category: "collision-repair",
    brand: "LINICH",
    image: "/linich-spot-lcr70.png",
    description: "Dual-function spot welder and dent puller with temperature-controlled air cooling.",
    specs: { "Current": "13.5 kA", "Power": "47.3 kVA" },
    features: ["Spring balancer compatible", "Heavy-duty duty cycle", "User-friendly control"],
    application: "Structural welding, dent pulling",
    cta: "Enquire Now",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "body-3",
    name: "10 Ton Body Frame Straightener",
    sku: "BFS-10T",
    category: "collision-repair",
    brand: "LINICH",
    image: "/body-frame-straightener.png",
    description: "Heavy-duty chassis straightening system with 10-ton hydraulic pump and swinging tower.",
    specs: { "Force": "10 Ton", "Tower": "Swinging" },
    features: ["Hydraulic tower", "Multiple pulling points", "Universal anchoring"],
    application: "Chassis alignment",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "body-4",
    name: "10 Ton Body Puller Kit",
    sku: "BPK-10T",
    category: "collision-repair",
    brand: "LINICH",
    image: "/10t-body-puller-kit.png",
    description: "Complete hydraulic pulling solution for collision repair, including various attachments.",
    specs: { "Capacity": "10 Ton" },
    features: ["Portable carry case", "Complete ram set", "Extension tubes included"],
    application: "Panel pulling",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "body-5",
    name: "CAR-O-LINER CM 250 MIG/MAG Welder",
    sku: "CAR-CM250",
    category: "collision-repair",
    brand: "CAR-O-LINER",
    image: "/car-o-liner-cm250.png",
    description: "Heavy-duty 250 Amp automotive welding machine designed for ease of use in body shops.",
    specs: { "Current": "250A", "Voltage": "1-Phase" },
    features: ["Spatter-free technology", "Simple parameters adjustment", "Integrated torch holder"],
    application: "Body shop welding",
    cta: "Enquire Now",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "body-6",
    name: "CAR-O-LINER CTR 9 Inverter Spot Welder",
    sku: "CAR-CTR9",
    category: "collision-repair",
    brand: "CAR-O-LINER",
    image: "/car-o-liner-ctr9.png",
    description: "Fully automatic inverter spot welder with a lightweight articulated arm.",
    specs: { "Type": "Automatic Inverter" },
    features: ["Telescopic arm", "355° swivel handle", "High pressure C-tong"],
    application: "Structural factory-spec spot welding",
    cta: "Enquire Now",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "body-7",
    name: "CAR-O-LINER CRX Spot Welder",
    sku: "CAR-CRX",
    category: "collision-repair",
    brand: "CAR-O-LINER",
    image: "/car-o-liner-crx.png",
    description: "Cost-effective inverter spot welder for efficient two-sided spot welding.",
    specs: { "Technology": "Inverter" },
    features: ["Lightweight design", "Powerful output", "Ease of operation"],
    application: "Quick panel repair",
    cta: "Enquire Now",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "body-8",
    name: "Hydraulic Coil Spring Compressor",
    sku: "GEN-HCSC",
    category: "collision-repair",
    brand: "Generic",
    image: "/hydraulic-coil-spring-compressor.png",
    description: "Professional hydraulic-assisted coil spring compressor with strong steel frame.",
    specs: { "System": "Hydraulic" },
    features: ["Safe spring removal", "Universal clamp", "Strong safety base"],
    application: "Suspension work",
    cta: "Enquire Now",
    hsn: "8425",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 3. WELDING & CUTTING
  // ========================
  {
    id: "weld-1",
    name: "LINICH MW 250 MIG/MAG Welding Machine",
    sku: "LIN-MW250",
    category: "welding",
    brand: "LINICH",
    image: "/linich-mw250.png",
    description: "High-performance step-regulated MIG/MAG welding machine with optimized inductor.",
    specs: { "Model": "MW 250", "Regulation": "Step-regulated" },
    features: ["Spatter-free welding", "Energy efficient", "Robust build quality"],
    application: "Industrial fabrication",
    cta: "Enquire Now",
    hsn: "8515",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "weld-2",
    name: "DeWALT 13mm Impact Drill – 750W",
    sku: "DW-ID-750",
    category: "welding",
    brand: "DeWALT",
    image: "/dewalt-impact-drill.png",
    description: "Professional high-performance impact drill designed for demanding metal and concrete work.",
    specs: { "Power": "750W", "Chuck": "13mm" },
    features: ["Variable speed", "Heavy-duty gear case", "Ergonomic side handle"],
    application: "Workshop drilling",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "weld-3",
    name: "DeWALT Angle Grinder",
    sku: "DW-AG-850",
    category: "welding",
    brand: "DeWALT",
    image: "/dewalt-angle-grinder-v3.png",
    description: "Ergonomic angle grinder for efficient cutting and grinding tasks in fabrication.",
    specs: { "Power": "850W", "Disc": "100mm" },
    features: ["Brushless motor technology", "Burst-proof guard", "Side handle"],
    application: "Metal grinding",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "weld-4",
    name: "Bosch Rotary Drill GSB 600",
    sku: "BOSCH-GSB600",
    category: "welding",
    brand: "Bosch",
    image: "/bosch-rotary-drill-gsb600.png",
    description: "Professional 600W rotary drill with compact and ergonomic design.",
    specs: { "Power": "600W", "Chuck": "13mm" },
    features: ["Soft grip handle", "Forward/reverse bit rotation", "Depth stop"],
    application: "Precision drilling",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "weld-5",
    name: "Bosch Heat Gun GHG 180",
    sku: "BOSCH-GHG180",
    category: "welding",
    brand: "Bosch",
    image: "/bosch-heat-gun-ghg180.png",
    description: "Powerful heat gun with two-stage temperature control for heating applications.",
    specs: { "Power": "1800W", "Temp": "Max 550°C" },
    features: ["Stable stand for safe use", "Ergonomic D-handle", "Rapid heating"],
    application: "Bending, shrinking, paint removal",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "weld-6",
    name: "Bosch Angle Grinder GWS 800",
    sku: "BOSCH-GWS800",
    category: "welding",
    brand: "Bosch",
    image: "/bosch-angle-grinder-gws800-v2.png",
    description: "Compact 800W angle grinder with 11,000 rpm no-load speed.",
    specs: { "Power": "800W", "RPM": "11000" },
    features: ["Lightweight body", "Efficient cooling", "Protective guard"],
    application: "Cutting and grinding",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 4. AIR, CLEANING & UTILITIES
  // ========================
  {
    id: "util-1",
    name: "LINICH Industrial Air Compressor",
    sku: "LIN-AIR",
    category: "cleaning",
    brand: "LINICH",
    image: "/linich-air-compressor.png",
    description: "Heavy-duty industrial air compressor designed for continuous workshop operation.",
    specs: { "Type": "Piston Industrial", "Stages": "Multi-stage" },
    features: ["High output CFM", "Thermal overload protection", "Large storage tank"],
    application: "Pneumatic tool supply",
    cta: "Enquire Now",
    hsn: "8414",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "util-2",
    name: "LINICH Industrial Vacuum Cleaner",
    sku: "LIN-VAC",
    category: "cleaning",
    brand: "LINICH",
    image: "/linich-vacuum-dry-wet.png",
    description: "Heavy-duty industrial dry/wet vacuum cleaner available in 30L and 80L models.",
    specs: { "Capacity": "30L / 80L", "Function": "Wet & Dry" },
    features: ["Stainless steel tank", "Low noise motor", "Full accessory kit"],
    application: "Workshop cleaning",
    cta: "Enquire Now",
    hsn: "8508",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "util-3",
    name: "3M Clean Sanding System",
    sku: "3M-SANDS",
    category: "cleaning",
    brand: "3M",
    image: "/3m-clean-sanding-system.png",
    description: "Complete dust-free sanding solution for automotive refinishing shops.",
    specs: { "System": "Dust-free", "Mobility": "Mobile cart" },
    features: ["HEPA filtration", "Automatic on/off", "Anti-static hose"],
    application: "Body shop prep",
    cta: "Enquire Now",
    hsn: "8421",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "util-4",
    name: "3M Performance Spray Gun",
    sku: "3M-PS-GUN",
    category: "cleaning",
    brand: "3M",
    image: "/3m-performance-spray-gun-v2.png",
    description: "Advanced lightweight spray gun designed for high efficiency and consistent results.",
    specs: { "Material": "High-impact composite", "Type": "HVLP/Compliant" },
    features: ["Quick change nozzles", "Lightest in class", "Superior atomization"],
    application: "Automotive painting",
    cta: "Enquire Now",
    hsn: "8424",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "util-5",
    name: "PCL SUMO Nitrogen Inflation System",
    sku: "PCL-SUMO-NS",
    category: "cleaning",
    brand: "PCL",
    image: "/pcl-sumo-nitrogen-system-v2.png",
    description: "Industrial-grade nitrogen generator for precise automotive tyre inflation.",
    specs: { "Output": "High purity Nitrogen", "Display": "Digital" },
    features: ["Automatic operation", "Pressure stability", "Internal storage tank"],
    application: "Tyre shops",
    cta: "Enquire Now",
    hsn: "8419",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "util-6",
    name: "Infrared Paint Dryer",
    sku: "GEN-IRD",
    category: "cleaning",
    brand: "Generic",
    image: "/infrared-paint-dryer.png",
    description: "Efficient infrared paint curing system with adjustable height and angles.",
    specs: { "Lamps": "Multi-lamp", "Control": "Electronic timer" },
    features: ["Gold coating tubes", "Automatic distance sensor", "Even heat distribution"],
    application: "Paint curing",
    cta: "Enquire Now",
    hsn: "8419",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 5. PAINT, POLISHING & FINISHING
  // ========================
  {
    id: "paint-1",
    name: "SATAjet 1000 IC Spray Gun",
    sku: "SATA-1000-IC",
    category: "painting",
    brand: "SATA",
    image: "/satajet-1000-ic.png",
    description: "Professional industrial spray gun for diverse coating tasks with high-quality results.",
    specs: { "Cup": "QCC", "Type": "Industrial" },
    features: ["Ergonomic handle", "Easy cleanup", "Consistent spray pattern"],
    application: "Refinishing, industrial coating",
    cta: "Enquire Now",
    hsn: "8424",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "paint-2",
    name: "SATA Full Face Respiratory Mask",
    sku: "SATA-MASK",
    category: "painting",
    brand: "SATA",
    image: "/sata-full-face-mask.png",
    description: "Complete facial protection for paint operations with comfortable breathing valves.",
    specs: { "Type": "Full Face", "Class": "PPE" },
    features: ["Wide view visor", "Easy seal check", "Replaceable cartridges"],
    application: "Paint booth safety",
    cta: "Enquire Now",
    hsn: "9020",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "paint-3",
    name: "DeVilbiss DV1 Basecoat Spray Gun",
    sku: "DVB-DV1",
    category: "painting",
    brand: "DeVilbiss",
    image: "/devilbiss-dv1-basecoat.png",
    description: "The ultimate basecoat spray system with revolutionary air management and atomization.",
    specs: { "Tech": "DV1 Atomization", "Body": "Optimized ergonomics" },
    features: ["Silent action trigger", "Low maintenance", "Perfect color match results"],
    application: "Premium basecoat application",
    cta: "Enquire Now",
    hsn: "8424",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "paint-4",
    name: "DeVilbiss PRO AIR-2 Filter",
    sku: "DVB-AIR2",
    category: "painting",
    brand: "DeVilbiss",
    image: "/devilbiss-pro-air-2.png",
    description: "High-spec air filtration system for breathing-quality workshop air.",
    specs: { "Filtration": "0.01 micron", "Flow": "High CFM" },
    features: ["Dual outlets", "Rolling diaphragm regulator", "Auto drain"],
    application: "Compressed air purification",
    cta: "Enquire Now",
    hsn: "8421",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "paint-5",
    name: "Mirka Automotive Refinishing System",
    sku: "MIR-REF-SYS",
    category: "painting",
    brand: "Mirka",
    image: "/mirka-maxshine-refinishing-system.png",
    description: "Integrated mobile workstation for professional sanding and finishing tasks.",
    specs: { "Setup": "Modular Mobile Cart" },
    features: ["Dust-free sanding", "Compact layout", "Full accessory storage"],
    application: "High-end body shops",
    cta: "Enquire Now",
    hsn: "8424",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "paint-6",
    name: "Menzerna Polishing System",
    sku: "MENZ-POL-SYS",
    category: "painting",
    brand: "Menzerna",
    image: "/menzerna-polishing-system-v2.png",
    description: "Complete professional compound kit for cutting, polishing, and glass-like finishes.",
    specs: { "Kit": "Multi-stage set" },
    features: ["VOC-free options", "Silicone free", "Consistent grit performance"],
    application: "Detailing and paint correction",
    cta: "Enquire Now",
    hsn: "3405",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "paint-7",
    name: "REXTER Performance Paint Gun",
    sku: "REX-PG",
    category: "painting",
    brand: "Rexter",
    image: "/rexter-performance-paint-gun-v2.png",
    description: "Precision spray gun with uniform pattern for automotive refinishing.",
    specs: { "Finish": "Chrome/Copper" },
    features: ["Adjustable flow", "High transfer efficiency", "Ergonomic body"],
    application: "Body refinishing",
    cta: "Enquire Now",
    hsn: "8424",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 6. TYRE & INFLATION
  // ========================
  {
    id: "tyre-1",
    name: "ACCURA Compact Digital Inflator",
    sku: "ACC-D60",
    category: "tyre-service",
    brand: "ACCURA",
    image: "/accura-compact-tyre-inflator.png",
    description: "Wall-mounted high-accuracy digital tyre inflator for service workshops.",
    specs: { "Display": "Touch Screen Digital", "Mount": "Wall-mounted" },
    features: ["Auto-start inflation", "High pressure support (D60HP)", "Safe inflate tech"],
    application: "Service stations",
    cta: "Enquire Now",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "tyre-2",
    name: "ACCURA QUBE Tyre Inflator",
    sku: "ACC-QUBE",
    category: "tyre-service",
    brand: "ACCURA",
    image: "/accura-qube-tyre-inflator.png",
    description: "Modern square-design digital tyre inflator for quick service bays.",
    specs: { "Design": "QUBE Square", "Accuracy": "High-precision" },
    features: ["Fast inflation cycle", "Electronic calibration", "Compact footprint"],
    application: "Tyre shops, quick bays",
    cta: "Enquire Now",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "tyre-3",
    name: "Handheld Digital Tyre Inflator",
    sku: "GEN-DTI",
    category: "tyre-service",
    brand: "Generic",
    image: "/digital-tyre-inflator-handheld-v2.png",
    description: "Portable digital gauge and inflator for precise on-the-go pressure management.",
    specs: { "Type": "Portable Digital", "Display": "Backlit" },
    features: ["Auto shut-off", "Pressure bleed valve", "Robust rubber boot"],
    application: "Emergency service, workshops",
    cta: "Enquire Now",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 7. POWER TOOLS
  // ========================
  {
    id: "pwr-1",
    name: "Bosch High Pressure Washer GHP 5-65",
    sku: "BOSCH-GHP565",
    category: "power-tools",
    brand: "Bosch",
    image: "/bosch-pressure-washer-ghp5-65-v2.png",
    description: "Top-end professional high pressure washer with steel-reinforced hose.",
    specs: { "Pressure": "160 bar", "Power": "2400W" },
    features: ["Induction motor", "Brass pump", "Variable pressure adjust"],
    application: "Heavy duty cleaning",
    cta: "Enquire Now",
    hsn: "8424",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "pwr-2",
    name: "Bosch High Pressure Washer GHP 5-13C",
    sku: "BOSCH-GHP513",
    category: "power-tools",
    brand: "Bosch",
    image: "/bosch-pressure-washer-ghp5-13c-v2.png",
    description: "Compact professional pressure washer for mobile service tasks.",
    specs: { "Pressure": "140 bar", "Power": "2300W" },
    features: ["Self-priming", "Ceramic coated pistons", "Mobile carry frame"],
    application: "Mobile cleaning",
    cta: "Enquire Now",
    hsn: "8424",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "pwr-3",
    name: "Bosch Metal Polisher GPO 12 CE",
    sku: "BOSCH-GPO12",
    category: "power-tools",
    brand: "Bosch",
    image: "/bosch-polisher-gpo12ce-v2.png",
    description: "Professional metal surface finisher with electronic speed control.",
    specs: { "Power": "1400W", "Disc": "180mm" },
    features: ["D-handle", "Variable speed trigger", "Overload protection"],
    application: "Metal polishing",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "pwr-4",
    name: "Bosch Cordless Impact Wrench",
    sku: "BOSCH-CIW-PRO",
    category: "power-tools",
    brand: "Bosch",
    image: "/bosch-cordless-impact-wrench-v2.png",
    description: "High-torque 18V cordless impact wrench for heavy fastening.",
    specs: { "Voltage": "18V", "Torque": "High-torque" },
    features: ["Brushless motor", "Variable speed", "Compact head design"],
    application: "Wheel changes, structural assembly",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 8. MEASURING & DIAGNOSTIC
  // ========================
  {
    id: "meas-1",
    name: "Fluke Digital Multimeter",
    sku: "FLUKE-117",
    category: "measurement",
    brand: "Fluke",
    image: "/fluke-professional-multimeter-v2.png",
    description: "Professional digital multimeter for accurate electrical troubleshooting.",
    specs: { "Brand": "Fluke", "Cat": "III 600V" },
    features: ["Non-contact voltage", "Auto-V/LoZ function", "Large white LED backlight"],
    application: "Electrical diagnostics",
    cta: "Enquire Now",
    hsn: "9030",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "meas-2",
    name: "Mitutoyo Outside Micrometer",
    sku: "MIT-OM-25",
    category: "measurement",
    brand: "Mitutoyo",
    image: "/mitutoyo-micrometer-v2.png",
    description: "World-standard precision micrometer for external measurements.",
    specs: { "Accuracy": "0.01mm", "Brand": "Mitutoyo" },
    features: ["Smooth spindle", "Clear scale", "Carbide measuring faces"],
    application: "Engine component sizing",
    cta: "Enquire Now",
    hsn: "9017",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "meas-3",
    name: "Blue-Point Radiator Tester Kit",
    sku: "BP-RPT",
    category: "measurement",
    brand: "Blue Point",
    image: "/blue-point-radiator-tester-v2.png",
    description: "Complete radiator pressure test kit for cooling system leak detection.",
    specs: { "Adapters": "Universal multi-set" },
    features: ["Pressure pump with gauge", "Heavy duty storage case", "Quick release coupling"],
    application: "Cooling system diagnosis",
    cta: "Enquire Now",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "meas-4",
    name: "JTC Oil Pressure Tester",
    sku: "JTC-OPT",
    category: "measurement",
    brand: "JTC",
    image: "/jtc-oil-pressure-tester-v3.png",
    description: "Engine oil pressure diagnostic kit with clear gauge and adapters.",
    specs: { "Brand": "JTC", "Gauge": "0-100 PSI" },
    features: ["Double scale gauge", "Fitted case", "Flexible hose"],
    application: "Engine health checks",
    cta: "Enquire Now",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "meas-5",
    name: "JTC Diesel Compressor Tester",
    sku: "JTC-DCT",
    category: "measurement",
    brand: "JTC",
    image: "/jtc-diesel-compressor-tester-v3.png",
    description: "Diesel engine compression tester with specialized injector dummy adapters.",
    specs: { "Engine": "Diesel", "Pressure": "60 Bar" },
    features: ["Glow plug adapters", "Injector adapters", "Large gauge"],
    application: "Diesel diagnostics",
    cta: "Enquire Now",
    hsn: "9026",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "meas-6",
    name: "Digital Vernier Caliper",
    sku: "GEN-VC-DIG",
    category: "measurement",
    brand: "Generic",
    image: "/stainless-vernier-caliper-v3.png",
    description: "Stainless steel digital vernier caliper for high-precision workshop measurements.",
    specs: { "Material": "Stainless Steel", "Accuracy": "±0.02mm" },
    features: ["External/Internal/Depth", "Metric/Inch switch", "Zero setting"],
    application: "Precision machining",
    cta: "Enquire Now",
    hsn: "9017",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "meas-7",
    name: "Precision Cylinder Bore Gauge",
    sku: "GEN-SBG",
    category: "measurement",
    brand: "Generic",
    image: "/precision-bore-gauge-v2.png",
    description: "Dial-indicator bore gauge for measuring cylinder internal diameters.",
    specs: { "Type": "Dial indicator" },
    features: ["Multiple spacer pins", "Insulated handle", "Self-centering"],
    application: "Engine reconditioning",
    cta: "Enquire Now",
    hsn: "9017",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "meas-8",
    name: "Digital Torque Wrench",
    sku: "GEN-DTW",
    category: "measurement",
    brand: "Generic",
    image: "/digital-torque-wrench-v2.png",
    description: "High-precision digital torque wrench with audible alerts for critical fastening.",
    specs: { "Alert": "Buzzer + LED" },
    features: ["Memory recall", "Peak/Track mode", "Battery operated"],
    application: "Precision bolt tightening",
    cta: "Enquire Now",
    hsn: "8204",
    minOrderQty: 1,
    inStock: true
  },

  // ========================
  // 9. HAND TOOLS & ACCESSORIES
  // ========================
  {
    id: "hand-1",
    name: "Standard Bench Vise",
    sku: "GEN-BV-HD",
    category: "hand-tools",
    brand: "Generic",
    image: "/heavy-duty-bench-vise-v2.png",
    description: "Rugged cast iron bench vise with swivel base for secure workshop clamping.",
    specs: { "Base": "360° Swivel" },
    features: ["Replaceable jaws", "Large anvil surface", "Durable lead screw"],
    application: "General clamping",
    cta: "Enquire Now",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-2",
    name: "Professional Air Ratchet",
    sku: "GEN-AR-PRO",
    category: "hand-tools",
    brand: "Generic",
    image: "/professional-air-ratchet-v2.png",
    description: "Compact air ratchet for fast removal and installation of threaded fasteners.",
    specs: { "Mechanism": "Twin-hammer", "Type": "Pneumatic" },
    features: ["Ball bearing construction", "Forward/Reverse lever", "Narrow head design"],
    application: "Engine bay fasteners",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-3",
    name: "Professional Chisel Set",
    sku: "GEN-CHS-SET",
    category: "hand-tools",
    brand: "Generic",
    image: "/professional-chisel-set-v2.png",
    description: "Hardened steel chisel and punch set for mechanical and metalwork tasks.",
    specs: { "Material": "Chrome Vanadium" },
    features: ["Precision edges", "Anti-mushroom head", "Carry pouch included"],
    application: "Metal cutting/punching",
    cta: "Enquire Now",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-4",
    name: "Universal Bearing Puller Set",
    sku: "GEN-BPS-SET",
    category: "hand-tools",
    brand: "Generic",
    image: "/bearing-puller-kit-pro-v2.png",
    description: "Diverse puller set for removing internal and external bearings safely.",
    specs: { "Set": "Multi-piece" },
    features: ["Chrome finish", "High torque bolts", "Storage case"],
    application: "Bearing removal",
    cta: "Enquire Now",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-5",
    name: "Door and Trim Panel Tool Set",
    sku: "GEN-DTP-SET",
    category: "hand-tools",
    brand: "Generic",
    image: "/door-trim-panel-set-v2.png",
    description: "Non-marring nylon tool set for safe disassembly of car interiors.",
    specs: { "Material": "Impact resistant Nylon" },
    features: ["Prevents panel scratches", "Multi-angle tools", "Slim profile"],
    application: "Interior removal",
    cta: "Enquire Now",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-6",
    name: "High Pressure Blow Gun",
    sku: "GEN-BG-L",
    category: "hand-tools",
    brand: "Generic",
    image: "/high-pressure-blow-gun-v2.png",
    description: "Powerful air blow gun for cleaning debris and drying parts in the workshop.",
    specs: { "Type": "Lever operated" },
    features: ["Long angled nozzle", "Integrated hook", "Ergonomic trigger"],
    application: "General workshop cleaning",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-7",
    name: "Industrial Sealant Gun",
    sku: "GEN-SG-IND",
    category: "hand-tools",
    brand: "Generic",
    image: "/industrial-sealant-gun-v2.png",
    description: "Professional sealant and caulking gun with high thrust ratio for thick materials.",
    specs: { "Construction": "Heavy-duty steel" },
    features: ["Non-drip function", "Rotatable cradle", "Puncture tool included"],
    application: "Glass and body sealing",
    cta: "Enquire Now",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-8",
    name: "Auto Glass Cutting Cable Set",
    sku: "GEN-GCC-SET",
    category: "hand-tools",
    brand: "Generic",
    image: "/glass-cutting-cable-set-v2.png",
    description: "Braided steel wire set for cutting through windshield sealant bonds.",
    specs: { "Material": "Braided steel" },
    features: ["Comfort handles", "Easy setup", "Low breakage rate"],
    application: "Windshield removal",
    cta: "Enquire Now",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-9",
    name: "Dual Suction Cup Lifter",
    sku: "GEN-SC-DUAL",
    category: "hand-tools",
    brand: "Generic",
    image: "/dual-suction-cup-v2.png",
    description: "Professional vacuum handling tools for glass panels and body straightening.",
    specs: { "Cups": "Two-cup design" },
    features: ["Fast release levers", "Safety grip", "Durable composite body"],
    application: "Glass handling, dent repair",
    cta: "Enquire Now",
    hsn: "8205",
    minOrderQty: 1,
    inStock: true
  },
  {
    id: "hand-10",
    name: "Pneumatic Air Riveter",
    sku: "GEN-AR-PNEU",
    category: "hand-tools",
    brand: "Generic",
    image: "/pneumatic-air-riveter-v2.png",
    description: "Industrial air riveter for high-speed fastening tasks in body work.",
    specs: { "Nozzles": "4 sizes included" },
    features: ["Mandrel collector", "Shock-proof design", "Quiet operation"],
    application: "Sheet metal fastening",
    cta: "Enquire Now",
    hsn: "8467",
    minOrderQty: 1,
    inStock: true
  }
]

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId)
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter((p) => p.brand === brand)
}

export function getTopProducts(count = 10): Product[] {
  return products.slice(0, count)
}

export function getOfferProducts(): Product[] {
  return products.filter((p) => p.isOffer)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.brand.toLowerCase().includes(lowercaseQuery) ||
      p.sku.toLowerCase().includes(lowercaseQuery),
  )
}
